# Generated by Django 3.1.3 on 2021-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('nascimento', models.DateField()),
                ('genero', models.CharField(max_length=1)),
                ('cor', models.CharField(max_length=1)),
                ('relacionamento', models.CharField(max_length=1)),
                ('instrucao', models.IntegerField()),
                ('trabalho_estudo', models.IntegerField()),
                ('funcao_unifeso', models.IntegerField()),
                ('moradia_caracteristicas', models.IntegerField()),
                ('residencia_adequada', models.IntegerField()),
                ('tipo_conexao', models.IntegerField()),
                ('tipo_rede', models.IntegerField()),
                ('dispositivo_usado', models.IntegerField()),
                ('tipo_usuario', models.IntegerField()),
                ('trocou_perfil_usuario', models.CharField(max_length=1)),
                ('equipamento_home_office', models.CharField(max_length=1)),
                ('apps_utilizados', models.IntegerField()),
                ('so_utilizado', models.IntegerField()),
                ('utilizou_virtualidade', models.CharField(max_length=1)),
                ('virtual_atividade', models.IntegerField()),
                ('dificuldade_uso_app', models.CharField(max_length=1)),
                ('contatar_suporte_app', models.CharField(max_length=1)),
                ('sat_serv_tel', models.CharField(max_length=1)),
                ('sat_serv_internet', models.CharField(max_length=1)),
                ('sat_serv_tv', models.CharField(max_length=1)),
                ('sat_serv_luz', models.CharField(max_length=1)),
                ('sat_serv_streaming', models.CharField(max_length=1)),
                ('sat_serv_finan', models.CharField(max_length=1)),
                ('sat_serv_gov', models.CharField(max_length=1)),
                ('sat_serv_univer', models.CharField(max_length=1)),
            ],
        ),
    ]
