# Generated by Django 3.1.3 on 2021-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dados',
            options={'verbose_name': 'Dados', 'verbose_name_plural': 'Dados'},
        ),
        migrations.AlterField(
            model_name='dados',
            name='apps_utilizados',
            field=models.IntegerField(choices=[('1', 'Facebook'), ('2', 'Linkedin'), ('3', 'Youtube'), ('4', 'Skype'), ('5', 'Snapchat'), ('6', 'Twitter'), ('7', 'Vimeo'), ('8', 'Whatsaap'), ('9', 'Netflix'), ('10', 'Amazon Prime Video'), ('11', 'Disney+'), ('12', 'Globoplay'), ('13', 'Paramount+'), ('14', 'Telegram'), ('15', 'Instagram'), ('16', 'Hangout'), ('17', 'Bible Youversion'), ('18', 'ResearchGate'), ('19', 'Flickr'), ('20', 'Tiktok'), ('21', 'E-mail'), ('22', 'Kindle'), ('23', 'Waze'), ('24', 'Cifra Club'), ('25', 'Aplicativos para acessar instituições financeiras'), ('26', 'Aplicativos para o aprendizado de idiomas')], verbose_name='Quais aplicativos ou software você utiliza? (Pode escolher mais de uma opção)'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='contatar_suporte_app',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Você precisou contatar o suporte ao usuário de algum software, aplicativo ou sistema que você fez uso?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='cor',
            field=models.CharField(choices=[('B', 'Branca'), ('P', 'Parda'), ('N', 'Preta'), ('A', 'Amarela')], max_length=1, verbose_name='Com que cor você se identifica?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dificuldade_uso_app',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Você teve dificuldades em utilizar aplicativos/software/sistemas durante o período de confinamento?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='dispositivo_usado',
            field=models.IntegerField(choices=[(1, 'Celular ou Smartphone'), (2, 'Computador ou notebook.'), (3, 'Tablet'), (4, 'Outro')], verbose_name='Qual dispositivo que você mais utilizada para navegar na internet? (Tarefas cotidianas, redes sociais e trabalho)'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='equipamento_home_office',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Você possui os equipamentos necessários para trabalhar em home office?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='funcao_unifeso',
            field=models.IntegerField(choices=[(1, 'Estudante de curso de graduação.'), (2, 'Estudante de curso de pós-graduação/residência.'), (3, 'Docente.'), (4, 'Profissional de saúde.'), (5, 'Função administrativa.'), (6, 'Serviços gerais.'), (7, 'Outra.')], verbose_name='Assinale sua função principal na comunidade do UNIFESO (considere o maior número de horas na atividade desenvolvida):'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('M', 'Feminino'), ('M', 'Outro')], max_length=1, verbose_name='Com que gênero você se identifica?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='instrucao',
            field=models.IntegerField(choices=[(1, 'Ensino fundamental'), (2, 'Ensino médio'), (3, 'Ensino técnico'), (4, 'Ensino superior'), (5, 'Pós-graduação (especialização, mestrado ou doutorado)'), (6, 'Não sabe'), (7, 'Outro')], verbose_name='Qual é o seu nível máximo de estudos concluídos?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='moradia_caracteristicas',
            field=models.IntegerField(choices=[(1, 'Varanda ou terraço'), (2, 'Jardim privado'), (3, 'Outras áreas externas'), (4, 'Nenhum espaço exterior')], verbose_name='A casa/apartamento em que você está confinado tem alguma das seguintes características?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='relacionamento',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a) ou união estável'), ('D', 'Desquitado/a, separado/a judicialmente ou divorciado/a'), ('V', 'Viúvo/a')], max_length=1, verbose_name='Qual é o seu estado civil?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='residencia_adequada',
            field=models.IntegerField(choices=[(1, 'Nada'), (2, 'Um pouco'), (3, 'Moderadamente'), (4, 'Bastante'), (5, 'Muito')], verbose_name='Você acha que sua residência é adequada para enfrentar o confinamento? (quanto a espaço, luz, número de quartos, etc.)'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_finan',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados por aplicativos de instituições financeiras (Bancos, financiadoras, corretoras de valores...):'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_gov',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados por aplicativos de instituições governamentais (FGTS, Meu INSS, CDT entre outros...):'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_internet',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados pela companhia de internet:'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_luz',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados por aplicativos da companhia de Luz:'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_streaming',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados por aplicativos de serviços de streaming:'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_tel',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados pela companhia de telefone:'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_tv',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços prestados pela companhia de TV a cabo:'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='sat_serv_univer',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('O', 'Não fiz o uso desse serviço')], max_length=1, verbose_name='Conte-nos se você ficou satisfeito com os serviços online disponibilizados pela Universidade (Portal do aluno, ava, biblioteca online...):'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='so_utilizado',
            field=models.IntegerField(choices=[(1, 'Windows'), (2, 'Distribuição Linux'), (3, 'Mac OS'), (4, 'iOS'), (5, 'Android'), (6, 'Não sei especificar'), (7, 'Outro')], verbose_name='Quais os sistemas operacionais que você mais utiliza?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='tipo_conexao',
            field=models.IntegerField(choices=[(1, 'Banda larga (internet residencial ou corporativa)'), (2, 'Internet móvel 3G/4G'), (3, 'Internet via satélite'), (4, 'Não sei indicar'), (5, 'Outro(Especificar)')], verbose_name='Qual a sua conexão de internet ?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='tipo_rede',
            field=models.IntegerField(choices=[(1, 'Rede pública (faculdade, hospital, rodoviária, shopping)'), (2, 'Rede privada (redes empresariais e de segurança governamental)'), (3, 'Rede doméstica (redes fornecidas diretamente por provedores de internet)')], verbose_name='Tipo da rede que você costuma se conectar.'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Perfil de usuário iniciante, não possui uma boa familiaridade com o acesso à internet.'), (2, "Perfi'l de usuário intermediário (velocidade de conexão (até 200 mega) para fazer downloads e uploads que requerem uma melhor conexão"), (3, "Perfil d'e usuário completo internet rápida ou ultrarrápida para gaming, videoconferências com pessoas de outros países e outros serviços digitais inclusos, como plataformas streaming.")], verbose_name='Qual o seu perfil de usuário da internet?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='trabalho_estudo',
            field=models.IntegerField(choices=[(1, 'Estudante e empregado com carteira assinada'), (2, 'Dona/o de casa ou cuidador/a de pessoas dependentes'), (3, 'Empregado com contrato temporário'), (4, 'Empregado com carteira assinada'), (5, 'Empregador'), (6, 'Outro')], verbose_name='Qual é  a sua situação de trabalho/estudo?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='trocou_perfil_usuario',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Você precisou trocar o perfil de usuário da internet, durante o confinamento?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='utilizou_virtualidade',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Durante a pandemia do novo coronavírus você utilizou a virtualidade para substituir alguma de suas atividades cotidianas?'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='virtual_atividade',
            field=models.IntegerField(choices=[(1, 'Estudar/realizar atividades referentes apenas ao curso de graduação.'), (2, 'Estudar para qualificação profissional.'), (3, 'Trabalhar na modalidade online (home office).'), (4, 'Fazer compras (supermercado/farmácia/padaria/vestuário).'), (5, 'Pagar contas online (água/luz/telefone/condomínio).'), (6, 'Outra')], verbose_name='Caso tenha respondido SIM, assinale a(s) atividade(s) desenvolvida(s) por você  (pode marcar mais de uma)'),
        ),
    ]
